# -*- coding: utf-8 -*-
"""
Содержимое сайта Math for Data Science.

Каждая формула — ровно четыре пункта: что это, где используется,
как используется, пример. Длинных объяснений здесь быть не должно.

Добавить неделю: допиши словарь в WEEKS и запусти  python build_site.py
"""

# --------------------------------------------------------------------------- #
#  НЕДЕЛЯ 1 — t-критерий Стьюдента
# --------------------------------------------------------------------------- #

W1_FORMULAS = [
    dict(
        id="hyp",
        name_ru="Гипотезы и правило решения",
        name_en="Hypotheses and the decision rule",
        tex=r"H_0:\ \mu_1=\mu_2 \qquad H_1:\ \mu_1\neq\mu_2 \qquad |t|>t_{\text{crit}}",
        what_ru="Формальная запись того, что проверяем: H₀ — различий нет, H₁ — различия есть.",
        what_en="A formal statement of what is tested: H₀ — no difference, H₁ — there is one.",
        where_ru="С этой пары начинается любой статистический критерий.",
        where_en="Every statistical test starts with this pair.",
        how_ru="Считаем статистику, берём критическое значение по df и α, сравниваем модули.",
        how_en="Compute the statistic, look up the critical value by df and α, compare absolute values.",
        ex_ru="|t| = 8,38 > t_кр(0,05; 9) = 2,26 → H₀ отвергаем, различия значимы.",
        ex_en="|t| = 8.38 > t_crit(0.05; 9) = 2.26 → reject H₀, the difference is significant.",
        src="Лекция 1, слайды 9–11",
    ),
    dict(
        id="t-one",
        name_ru="t-критерий, одна выборка",
        name_en="One-sample t-test",
        tex=r"t=\frac{\bar{x}-\mu_0}{s/\sqrt{n}}\,,\qquad s=\sqrt{\frac{\sum (x_i-\bar{x})^2}{n-1}}\,,\qquad df=n-1",
        what_ru="Сравнивает среднее одной выборки с заданным числом.",
        what_en="Compares the mean of one sample with a given value.",
        where_ru="Когда есть норматив или эталон: «средний балл действительно равен 5?»",
        where_en="When there is a norm or reference value: “is the mean score really 5?”",
        how_ru="Найти x̄ и s, подставить, сравнить |t| с t_кр при df = n−1.",
        how_en="Find x̄ and s, substitute, compare |t| with t_crit at df = n−1.",
        ex_ru="x̄ = 5,4; s = 0,9; n = 10; μ₀ = 5 → t = 0,4 / 0,2846 = 1,41 < 2,26 → различий нет.",
        ex_en="x̄ = 5.4; s = 0.9; n = 10; μ₀ = 5 → t = 0.4 / 0.2846 = 1.41 < 2.26 → no difference.",
        src="Лекция 1, слайд 14",
    ),
    dict(
        id="t-paired",
        name_ru="t-критерий, зависимые (парные) выборки",
        name_en="Paired t-test (dependent samples)",
        tex=r"d_i=x_i-y_i\,,\quad \bar{d}=\frac{\sum d_i}{n}\,,\quad s_d=\sqrt{\frac{\sum (d_i-\bar{d})^2}{n-1}}\,,\quad t=\frac{\bar{d}}{s_d/\sqrt{n}}\,,\quad df=n-1",
        what_ru="Сравнивает «до» и «после» у одних и тех же объектов.",
        what_en="Compares “before” and “after” on the same subjects.",
        where_ru="Один и тот же человек измерен дважды: до тренинга и после.",
        where_en="The same person measured twice: before and after a treatment.",
        how_ru="Посчитать разности d_i, дальше — как одновыборочный тест для d̄ против нуля.",
        how_en="Compute the differences d_i, then run a one-sample test of d̄ against zero.",
        ex_ru="d̄ = 3,120; s_d = 1,177; n = 10 → t = 8,38 при t_кр = 2,26 → эффект значим.",
        ex_en="d̄ = 3.120; s_d = 1.177; n = 10 → t = 8.38 vs t_crit = 2.26 → the effect is significant.",
        src="Лекция 1, слайд 14; Assignment 1, Part I",
    ),
    dict(
        id="sd-practice",
        name_ru="S_d через суммы (формула практики)",
        name_en="S_d from sums (practice formula)",
        tex=r"S_d=\sqrt{\frac{\sum d^2-\dfrac{(\sum d)^2}{n}}{n(n-1)}}\,,\qquad t=\frac{\bar{d}}{S_d}",
        what_ru="Та же парная статистика, но считается через две суммы.",
        what_en="The same paired statistic, computed from two sums.",
        where_ru="В Practice 1; удобно, когда считаешь руками в столбик.",
        where_en="Used in Practice 1; convenient for hand calculation in a table.",
        how_ru="Заполнить столбцы d и d², взять Σd и Σd². Здесь S_d — уже стандартная ошибка, делить на √n не нужно.",
        how_en="Fill in columns d and d², take Σd and Σd². Here S_d is already the standard error — do not divide by √n.",
        ex_ru="Σd = 100; Σd² = 1006; n = 10 → S_d = 0,2582; t = 10 / 0,2582 = 38,73.",
        ex_en="Σd = 100; Σd² = 1006; n = 10 → S_d = 0.2582; t = 10 / 0.2582 = 38.73.",
        src="Practice 1 ADA-M.pdf, формула (35)",
    ),
    dict(
        id="t-ind",
        name_ru="t-критерий, независимые выборки (запись лекции)",
        name_en="Independent-samples t-test (lecture form)",
        tex=r"t=\frac{\bar{X}-\bar{Y}}{S_d}\,,\qquad S_d=\sqrt{\frac{S_X^2}{n_1}+\frac{S_Y^2}{n_2}}\,,\qquad df=n_1+n_2-2",
        what_ru="Сравнивает средние двух разных групп.",
        what_en="Compares the means of two different groups.",
        where_ru="Две независимые группы: контрольная и экспериментальная.",
        where_en="Two independent groups: control and experimental.",
        how_ru="Посчитать дисперсию каждой группы, разделить на объёмы, сложить и взять корень.",
        how_en="Compute each group's variance, divide by its size, add, take the square root.",
        ex_ru="n₁=9, X̄=526, S²=3579; n₂=8, Ȳ=638, S²=2596,29 → S_d = 26,874; t = −4,17; df = 15 → значимо.",
        ex_en="n₁=9, X̄=526, S²=3579; n₂=8, Ȳ=638, S²=2596.29 → S_d = 26.874; t = −4.17; df = 15 → significant.",
        src="Лекция 1, слайд 14; Assignment 1, Part I",
    ),
    dict(
        id="t-pooled",
        name_ru="Объединённая дисперсия (классический вариант)",
        name_en="Pooled variance (textbook form)",
        tex=r"s_p^2=\frac{(n_1-1)s_1^2+(n_2-1)s_2^2}{n_1+n_2-2}\,,\qquad t=\frac{\bar{x}_1-\bar{x}_2}{\sqrt{s_p^2\left(\dfrac{1}{n_1}+\dfrac{1}{n_2}\right)}}",
        what_ru="Тот же тест для независимых выборок, но дисперсии считаются равными.",
        what_en="The same independent-samples test, assuming equal variances.",
        where_ru="Основная форма в учебниках; в лекции дана версия с раздельными дисперсиями.",
        where_en="The standard textbook form; the lecture uses the separate-variances version.",
        how_ru="Усреднить дисперсии с весами (n−1), подставить в знаменатель.",
        how_en="Average the variances weighted by (n−1), then substitute into the denominator.",
        ex_ru="Те же данные → s_p² = 3120,4; t = −4,13 (лекционная формула даёт −4,17).",
        ex_en="Same data → s_p² = 3120.4; t = −4.13 (the lecture formula gives −4.17).",
        src="Учебник; сравнение с лекцией",
    ),
]

W1_LECTURE = [
    dict(
        h_ru="О чём курс", h_en="What the course is about",
        items_ru=["Анализ данных средствами компьютерных технологий.",
                  "Статистические пакеты и приближённые вычисления.",
                  "Возможности и ограничения конкретных методов обработки.",
                  "Стандарты обработки данных."],
        items_en=["Data analysis using computer technology.",
                  "Statistical packages and approximate computation.",
                  "Capabilities and limits of particular processing methods.",
                  "Data processing standards."],
        src="Лекция 1, слайд 2",
    ),
    dict(
        h_ru="Статистические программы", h_en="Statistical software",
        items_ru=["Платные: SPSS, Statistica, Minitab, SAS, STATA, MATLAB, EViews.",
                  "Бесплатные: R + RStudio, EpiInfo, SOFA, SEER-Stat, Deducer.",
                  "Excel — доступен всем, но возможности ограничены."],
        items_en=["Paid: SPSS, Statistica, Minitab, SAS, STATA, MATLAB, EViews.",
                  "Free: R + RStudio, EpiInfo, SOFA, SEER-Stat, Deducer.",
                  "Excel — available to everyone, but limited in scope."],
        src="Лекция 1, слайды 3–7",
    ),
    dict(
        h_ru="Стандарты качества данных", h_en="Data quality standards",
        items_ru=["Полнота — нет пропусков и неполных записей.",
                  "Точность — данные отражают реальность, без ошибок ввода.",
                  "Согласованность — единые форматы и единицы измерения."],
        items_en=["Completeness — no gaps or incomplete records.",
                  "Accuracy — data reflect reality, no input errors.",
                  "Consistency — uniform formats and units."],
        src="Лекция 1, слайд 8",
    ),
    dict(
        h_ru="Алгоритм выбора критерия", h_en="How to choose a test",
        items_ru=["Определить модель, подходящую для проверки предположения.",
                  "Прочитать описание метода, примеры и задачи.",
                  "Проверить ограничения критерия и возможность собрать данные.",
                  "Определить объём выборки и обеспечить к ней доступ.",
                  "Провести исследование и обработать данные по выбранному алгоритму.",
                  "Если ограничения не выполнены — вернуться на шаг назад."],
        items_en=["Pick the model that fits the assumption being tested.",
                  "Read the method description, examples and exercises.",
                  "Check the test's restrictions and whether the data can be collected.",
                  "Determine the sample size and secure access to it.",
                  "Run the study and process the data using the chosen algorithm.",
                  "If the restrictions cannot be met — go back a step."],
        src="Лекция 1, слайд 15",
    ),
]

# --------------------------------------------------------------------------- #
#  НЕДЕЛЯ 2 — меры изменчивости, критерий Фишера
# --------------------------------------------------------------------------- #

W2_FORMULAS = [
    dict(
        id="range",
        name_ru="Размах",
        name_en="Range",
        tex=r"R = x_{\max} - x_{\min}",
        what_ru="Расстояние между самым большим и самым маленьким значением.",
        what_en="The distance between the largest and the smallest value.",
        where_ru="Самая быстрая оценка разброса, первый взгляд на данные.",
        where_en="The quickest measure of spread, a first look at the data.",
        how_ru="Отсортировать выборку и вычесть минимум из максимума.",
        how_en="Sort the sample and subtract the minimum from the maximum.",
        ex_ru="2, 4, 4, 4, 5, 5, 7, 9 → R = 9 − 2 = 7.",
        ex_en="2, 4, 4, 4, 5, 5, 7, 9 → R = 9 − 2 = 7.",
        src="Лекция 2, слайды 2–3",
    ),
    dict(
        id="mad",
        name_ru="Среднее абсолютное отклонение",
        name_en="Mean absolute deviation",
        tex=r"\bar{d} = \frac{1}{n}\sum_{i=1}^{n}\left|x_i-\bar{x}\right|",
        what_ru="Средняя величина отклонения значений от среднего.",
        what_en="The average size of deviations from the mean.",
        where_ru="Когда нужен разброс в исходных единицах и без усиления выбросов.",
        where_en="When spread is needed in original units, without amplifying outliers.",
        how_ru="Найти x̄, взять модули отклонений, усреднить.",
        how_en="Find x̄, take absolute deviations, average them.",
        ex_ru="Тот же набор, x̄ = 5 → d̄ = 1,5.",
        ex_en="Same data, x̄ = 5 → d̄ = 1.5.",
        src="Лекция 2, слайды 2–3",
    ),
    dict(
        id="var",
        name_ru="Дисперсия",
        name_en="Variance",
        tex=r"\sigma^2=\frac{1}{N}\sum (x_i-\mu)^2 \qquad\qquad s^2=\frac{1}{n-1}\sum (x_i-\bar{x})^2",
        what_ru="Средний квадрат отклонения от среднего.",
        what_en="The mean squared deviation from the mean.",
        where_ru="Основа почти всех критериев: t, F, χ².",
        where_en="The basis of almost every test: t, F, χ².",
        how_ru="По всей совокупности делим на N, по выборке — на n−1 (поправка Бесселя).",
        how_en="Divide by N for a population, by n−1 for a sample (Bessel's correction).",
        ex_ru="2, 4, 4, 4, 5, 5, 7, 9 → σ² = 4,0; s² = 4,571.",
        ex_en="2, 4, 4, 4, 5, 5, 7, 9 → σ² = 4.0; s² = 4.571.",
        src="Лекция 2, слайд 1 (там S² записана с 1/n)",
    ),
    dict(
        id="sd",
        name_ru="Стандартное отклонение",
        name_en="Standard deviation",
        tex=r"s=\sqrt{s^2}=\sqrt{\frac{\sum (x_i-\bar{x})^2}{n-1}}",
        what_ru="Дисперсия, возвращённая в исходные единицы измерения.",
        what_en="The variance brought back to the original units.",
        where_ru="Везде, где надо записать результат как «среднее ± разброс».",
        where_en="Wherever a result is reported as “mean ± spread”.",
        how_ru="Извлечь корень из дисперсии.",
        how_en="Take the square root of the variance.",
        ex_ru="s² = 4,571 → s = 2,138.",
        ex_en="s² = 4.571 → s = 2.138.",
        src="Лекция 2, слайды 2–3",
    ),
    dict(
        id="cv",
        name_ru="Коэффициент вариации",
        name_en="Coefficient of variation",
        tex=r"V=\frac{s}{\bar{x}}\cdot 100\,\%",
        what_ru="Разброс, выраженный в процентах от среднего.",
        what_en="Spread expressed as a percentage of the mean.",
        where_ru="Сравнение разброса величин в разных единицах — роста и веса.",
        where_en="Comparing spread of quantities in different units — height and weight.",
        how_ru="Разделить s на x̄. Ориентир: V > 33 % — совокупность неоднородна.",
        how_en="Divide s by x̄. Rule of thumb: V > 33 % means the data are heterogeneous.",
        ex_ru="s = 2,138; x̄ = 5 → V = 42,8 % — набор неоднородный.",
        ex_en="s = 2.138; x̄ = 5 → V = 42.8 % — the data are heterogeneous.",
        src="Лекция 2, слайды 2–3",
    ),
    dict(
        id="f-test",
        name_ru="F-критерий Фишера",
        name_en="Fisher's F-test",
        tex=r"F=\frac{s_1^2}{s_2^2}\quad (s_1^2>s_2^2)\,,\qquad df_1=n_1-1\,,\quad df_2=n_2-1",
        what_ru="Сравнивает разброс двух выборок — равны ли дисперсии.",
        what_en="Compares the spread of two samples — are the variances equal?",
        where_ru="Проверка однородности групп; перед t-тестом для независимых выборок.",
        where_en="Checking group homogeneity; before an independent-samples t-test.",
        how_ru="Бо́льшую дисперсию всегда в числитель, сравнить с F_кр по двум df.",
        how_en="Always put the larger variance on top, compare with F_crit using both df.",
        ex_ru="s₁² = 25; s₂² = 16 → F = 1,56 < F_кр(0,05; 14; 11) = 2,74 → дисперсии равны.",
        ex_en="s₁² = 25; s₂² = 16 → F = 1.56 < F_crit(0.05; 14; 11) = 2.74 → variances are equal.",
        src="Лекция 2, слайд 1; Assignment 1, Part II",
    ),
    dict(
        id="fisher-exact",
        name_ru="Точный тест Фишера",
        name_en="Fisher's exact test",
        tex=r"p=\frac{(a+b)!\,(c+d)!\,(a+c)!\,(b+d)!}{n!\;a!\;b!\;c!\;d!}",
        what_ru="Точная вероятность получить такую таблицу 2×2, если связи нет.",
        what_en="The exact probability of getting such a 2×2 table if there is no association.",
        where_ru="Таблицы 2×2 с маленькими частотами, где χ² применять нельзя.",
        where_en="2×2 tables with small counts, where χ² is not applicable.",
        how_ru="Посчитать p данной таблицы и всех ещё более крайних, сложить.",
        how_en="Compute p for the observed table and all more extreme ones, then sum.",
        ex_ru="Таблица [[0, 10], [12, 2]] → p таблицы = 0,000034; двусторонний p = 0,000067 → связь значима.",
        ex_en="Table [[0, 10], [12, 2]] → p of the table = 0.000034; two-sided p = 0.000067 → significant.",
        src="Лекция 2, слайд 11",
    ),
]

W2_LECTURE = [
    dict(
        h_ru="Нулевая гипотеза", h_en="The null hypothesis",
        items_ru=["H₀ предполагает, что разница между генеральными параметрами групп равна нулю.",
                  "Наблюдаемые различия объявляются случайными, а не систематическими.",
                  "H₀ — то, что мы хотим опровергнуть; H₁ — экспериментальная гипотеза."],
        items_en=["H₀ assumes the difference between population parameters is zero.",
                  "Observed differences are declared random rather than systematic.",
                  "H₀ is what we want to refute; H₁ is the experimental hypothesis."],
        src="Лекция 2, слайды 8–9",
    ),
    dict(
        h_ru="Параметрические и непараметрические критерии",
        h_en="Parametric and non-parametric tests",
        items_ru=["Параметрические оценивают различия средних (t-критерий Стьюдента).",
                  "Непараметрические оценивают лишь средние тенденции (Розенбаум Q, Манн–Уитни U, φ Фишера).",
                  "Параметрические позволяют прямо оценить различия, но требуют нормального распределения."],
        items_en=["Parametric tests compare means (Student's t-test).",
                  "Non-parametric tests only compare general tendencies (Rosenbaum Q, Mann–Whitney U, Fisher's φ).",
                  "Parametric tests assess differences directly but require normality."],
        src="Лекция 2, слайд 10",
    ),
    dict(
        h_ru="Односторонний и двусторонний тест", h_en="One-tailed and two-tailed tests",
        items_ru=["Односторонний: H₁ задаёт направление (p₁ > p₂), учитываются только таблицы с разницей в эту сторону.",
                  "p-value будет меньше, чем в двустороннем, если предположение верно → тест чувствительнее.",
                  "Применяется, когда направление эффекта известно заранее."],
        items_en=["One-tailed: H₁ fixes the direction (p₁ > p₂); only tables differing that way are counted.",
                  "The p-value is smaller than in a two-tailed test if the assumption holds → more sensitive.",
                  "Used when the direction of the effect is known in advance."],
        src="Лекция 2, слайд 7",
    ),
]

# --------------------------------------------------------------------------- #
#  НЕДЕЛЯ 3 — анализ номинативных данных, χ² Пирсона
# --------------------------------------------------------------------------- #

W3_FORMULAS = [
    dict(
        id="chi2",
        name_ru="Критерий χ² Пирсона",
        name_en="Pearson's χ² test",
        tex=r"\chi^2=\sum \frac{(O_i-E_i)^2}{E_i}",
        what_ru="Мера расхождения наблюдаемых частот с ожидаемыми.",
        what_en="A measure of how far observed frequencies are from expected ones.",
        where_ru="Таблицы сопряжённости: есть ли связь между двумя качественными признаками.",
        where_en="Contingency tables: is there an association between two categorical variables?",
        how_ru="По каждой ячейке посчитать (O−E)²/E, всё сложить, сравнить с χ²_кр по df.",
        how_en="For each cell compute (O−E)²/E, sum them all, compare with χ²_crit at df.",
        ex_ru="Пример из лекции (3×3, N = 170) → χ² = 34,98 при χ²_кр(0,05; 4) = 9,5 → связь значима.",
        ex_en="Lecture example (3×3, N = 170) → χ² = 34.98 vs χ²_crit(0.05; 4) = 9.5 → significant.",
        src="Лекция 3, слайд 9 (на слайде обозначено Q вместо O)",
    ),
    dict(
        id="expected",
        name_ru="Ожидаемая частота",
        name_en="Expected frequency",
        tex=r"E_{ij}=\frac{R_i\cdot C_j}{N}",
        what_ru="Частота, которая была бы в ячейке при полном отсутствии связи.",
        what_en="The frequency a cell would have if there were no association at all.",
        where_ru="Первый шаг любого расчёта χ² — без E формулу не применить.",
        where_en="The first step of any χ² computation — without E the formula cannot be used.",
        how_ru="R_i — итог строки, C_j — итог столбца, N — общий итог. Считается для каждой ячейки.",
        how_en="R_i is the row total, C_j the column total, N the grand total. Computed for every cell.",
        ex_ru="30 × 73 / 170 = 12,88 ≈ 13 — совпадает с E, подписанным на слайде.",
        ex_en="30 × 73 / 170 = 12.88 ≈ 13 — matches the E written on the slide.",
        src="Лекция 3, слайд 9 (формулой не выписана, восстановлена из таблицы)",
    ),
    dict(
        id="df",
        name_ru="Число степеней свободы",
        name_en="Degrees of freedom",
        tex=r"df=(n_1-1)(n_2-1)",
        what_ru="Параметр, по которому выбирается строка в таблице критических значений.",
        what_en="The parameter that selects the row in the table of critical values.",
        where_ru="Нужен сразу после расчёта χ², перед сравнением с таблицей.",
        where_en="Needed right after computing χ², before comparing with the table.",
        how_ru="(число строк − 1) × (число столбцов − 1). Итоговые строка и столбец не считаются.",
        how_en="(rows − 1) × (columns − 1). Total row and column are not counted.",
        ex_ru="Таблица 3×3 → df = 2 × 2 = 4 → χ²_кр(0,05) = 9,5.",
        ex_en="A 3×3 table → df = 2 × 2 = 4 → χ²_crit(0.05) = 9.5.",
        src="Лекция 3, слайд 9",
    ),
    dict(
        id="chi2-rule",
        name_ru="Условия применения и вывод",
        name_en="Assumptions and conclusion",
        tex=r"E_{ij}>5\,,\qquad \chi^2>\chi^2_{\text{crit}}",
        what_ru="Когда критерий вообще работает и как читать результат.",
        what_en="When the test is valid at all, and how to read the result.",
        where_ru="Проверять до расчёта: качественные данные, независимые группы, ожидаемая частота больше 5.",
        where_en="Check before computing: categorical data, independent groups, expected counts above 5.",
        how_ru="Не применять при частоте в ячейке меньше 5, зависимых группах и абсолютных величинах (рост, вес, проценты).",
        how_en="Do not use with cell counts below 5, dependent groups, or continuous measures (height, weight, percentages).",
        ex_ru="χ² = 34,98 > 9,5 → H₀ отвергаем: степень нарушения влияет на исход операции.",
        ex_en="χ² = 34.98 > 9.5 → reject H₀: the severity level does affect the outcome.",
        src="Лекция 3, слайды 6–7",
    ),
    dict(
        id="chi2-dist",
        name_ru="Распределение χ²",
        name_en="The χ² distribution",
        tex=r"\chi^2_n=\sum_{i=1}^{n} Z_i^2\,,\ \ Z_i\sim N(0,1)\,;\qquad M\chi^2_n=n\,,\qquad D\chi^2_n=2n",
        what_ru="Сумма квадратов n независимых стандартных нормальных величин.",
        what_en="The sum of squares of n independent standard normal variables.",
        where_ru="Отсюда берутся критические значения в таблице.",
        where_en="This is where the table's critical values come from.",
        how_ru="Параметр один — число степеней свободы n; при n > 2 мода равна n − 2.",
        how_en="A single parameter — the degrees of freedom n; for n > 2 the mode is n − 2.",
        ex_ru="n = 4 → среднее 4, дисперсия 8, мода 2; асимметрия √(8/4) = 1,41.",
        ex_en="n = 4 → mean 4, variance 8, mode 2; skewness √(8/4) = 1.41.",
        src="Лекция 3, слайды 5, 11–12",
    ),
    dict(
        id="chi2-pdf",
        name_ru="Плотность распределения χ²",
        name_en="The χ² density function",
        tex=r"p_{\chi^2}(x)=\frac{x^{\,n/2-1}e^{-x/2}}{2^{\,n/2}\,\Gamma(n/2)}\,,\ x>0\,;\qquad p(x)=0\,,\ x\le 0",
        what_ru="Формула кривой, по которой вычисляются p-value.",
        what_en="The curve from which p-values are computed.",
        where_ru="Теоретическая часть; на практике берут готовую таблицу или калькулятор.",
        where_en="Theory only; in practice one uses a table or a calculator.",
        how_ru="Γ(n/2) — гамма-функция. При n ≤ 2 кривая убывает, при n > 2 имеет максимум.",
        how_en="Γ(n/2) is the gamma function. For n ≤ 2 the curve decreases, for n > 2 it has a peak.",
        ex_ru="При n → ∞ распределение приближается к нормальному со средним n и дисперсией 2n.",
        ex_en="As n → ∞ the distribution approaches a normal one with mean n and variance 2n.",
        src="Лекция 3, слайд 11",
    ),
    dict(
        id="gamma",
        name_ru="Гамма-распределение и связь с χ²",
        name_en="The gamma distribution and its link to χ²",
        tex=r"f(x)=\frac{\lambda^r x^{r-1}e^{-\lambda x}}{\Gamma(r)}\,,\quad \Gamma(r)=\int_0^{\infty}x^{r-1}e^{-x}dx\,;\qquad \mu=\frac{r}{\lambda}\,,\quad \sigma^2=\frac{r}{\lambda^2}",
        what_ru="Общее семейство распределений, частным случаем которого является χ².",
        what_en="The general family of distributions of which χ² is a special case.",
        where_ru="Объясняет, откуда взялась формула плотности χ².",
        where_en="Explains where the χ² density formula comes from.",
        how_ru="Подставить λ = ½ и r = n/2 — получится ровно плотность χ² с n степенями свободы.",
        how_en="Substitute λ = ½ and r = n/2 — you get exactly the χ² density with n degrees of freedom.",
        ex_ru="μ = r/λ = (n/2)/(½) = n, σ² = r/λ² = (n/2)/(¼) = 2n — совпадает с Mχ² и Dχ².",
        ex_en="μ = r/λ = (n/2)/(½) = n, σ² = r/λ² = (n/2)/(¼) = 2n — matches Mχ² and Dχ².",
        src="Лекция 3, слайды 2–4 (формулы 4.17–4.19)",
    ),
]

W3_LECTURE = [
    dict(
        h_ru="Когда применять χ² Пирсона", h_en="When Pearson's χ² applies",
        items_ru=["Анализ статистических различий.",
                  "Качественные данные: ранги, номинальные, бинарные (да / нет).",
                  "Две и более групп.",
                  "Количество наблюдений в каждой ячейке больше 5."],
        items_en=["Analysis of statistical differences.",
                  "Categorical data: ranks, nominal, binary (yes / no).",
                  "Two or more groups.",
                  "More than 5 observations in every cell."],
        src="Лекция 3, слайд 6",
    ),
    dict(
        h_ru="Когда не применять", h_en="When it does not apply",
        items_ru=["Частота в ячейке меньше 5.",
                  "Зависимые группы.",
                  "Абсолютные величины: рост, вес, проценты."],
        items_en=["Cell frequency below 5.",
                  "Dependent groups.",
                  "Continuous measures: height, weight, percentages."],
        src="Лекция 3, слайд 6",
    ),
    dict(
        h_ru="Как работает критерий", h_en="How the test works",
        items_ru=["Сравниваются реальные частоты (Observed) и ожидаемые «гипотетические» (Expected).",
                  "Малое расхождение — χ² не достиг критического значения — H₀ принимается.",
                  "Существенное расхождение — H₀ отвергается, различия статистически значимы."],
        items_en=["Observed frequencies are compared with expected “hypothetical” ones.",
                  "A small gap — χ² below the critical value — H₀ is accepted.",
                  "A large gap — H₀ is rejected, the differences are statistically significant."],
        src="Лекция 3, слайд 7",
    ),
    dict(
        h_ru="Пример 1 — комиссуротомия", h_en="Example 1 — commissurotomy",
        items_ru=["Фактор: степень нарушения кровообращения (II, III, IV). Исход: результат операции.",
                  "Таблица 3×3, N = 170; итоги по столбцам 73, 68, 29.",
                  "Ожидаемые частоты: 30 × 73 / 170 = 12,88; 30 × 68 / 170 = 12,0; 80 × 73 / 170 = 34,35.",
                  "χ² = 34,98 при df = 4; критическое 9,5 → влияние есть."],
        items_en=["Factor: severity of circulatory disorder (II, III, IV). Outcome: result of surgery.",
                  "A 3×3 table, N = 170; column totals 73, 68, 29.",
                  "Expected counts: 30 × 73 / 170 = 12.88; 30 × 68 / 170 = 12.0; 80 × 73 / 170 = 34.35.",
                  "χ² = 34.98 at df = 4; critical value 9.5 → the factor matters."],
        src="Лекция 3, слайды 8–9",
    ),
]

# --------------------------------------------------------------------------- #

WEEKS = [
    dict(n=1,
         title_ru="t-критерий Стьюдента",
         title_en="Student's t-test",
         sub_ru="Гипотезы, зависимые и независимые выборки",
         sub_en="Hypotheses, dependent and independent samples",
         source="Lecture 1 Math for Data Science, ADA-M.pptx · Practice 1 ADA-M.pdf",
         formulas=W1_FORMULAS, lecture=W1_LECTURE),
    dict(n=2,
         title_ru="Меры изменчивости и критерий Фишера",
         title_en="Measures of variability and Fisher's test",
         sub_ru="Разброс данных, сравнение дисперсий, точный тест",
         sub_en="Spread of data, comparing variances, the exact test",
         source="Lecture 2_Math_Data_Science.pptx",
         formulas=W2_FORMULAS, lecture=W2_LECTURE),
    dict(n=3,
         title_ru="Анализ номинативных данных, χ² Пирсона",
         title_en="Analysis of nominative data, Pearson's χ²",
         sub_ru="Таблицы сопряжённости, ожидаемые частоты, распределение χ²",
         sub_en="Contingency tables, expected frequencies, the χ² distribution",
         source="Lecture 3 ADA_M.pptx · Practice 3 ADA_M.pdf",
         formulas=W3_FORMULAS, lecture=W3_LECTURE),
]

# подписи интерфейса
UI = {
    "site_ru": "Математика для Data Science",
    "site_en": "Mathematics for Data Science",
    "formulas_ru": "Формулы", "formulas_en": "Formulas",
    "lecture_ru": "Лекция", "lecture_en": "Lecture",
    "week_ru": "Неделя", "week_en": "Week",
    "what_ru": "Что это", "what_en": "What it is",
    "where_ru": "Где используется", "where_en": "Where it is used",
    "how_ru": "Как используется", "how_en": "How it is used",
    "ex_ru": "Пример", "ex_en": "Example",
    "calc_ru": "Калькуляторы", "calc_en": "Calculators",
    "tables_ru": "Таблицы", "tables_en": "Tables",
    "home_ru": "Главная", "home_en": "Home",
    "source_ru": "Источник", "source_en": "Source",
}
