import type { Lesson } from "../types";

export const lesson: Lesson = {
  course: "prog",
  week: 10,
  minutes: 65,
  title: { en: "End-term quiz, EDA and a first look at R", ru: "Итоговый тест, разведочный анализ и первый взгляд на R" },
  summary: {
    en: "The quiz covers the whole course. The new material is exploratory analysis as a discipline, reproducibility as a deliverable, and enough R to read the tidyverse.",
    ru: "Тест закрывает весь курс. Новый материал — разведочный анализ как дисциплина, воспроизводимость как результат работы и столько R, чтобы читать tidyverse.",
  },
  goals: {
    en: [
      "Run an exploratory analysis as a repeatable procedure rather than improvisation",
      "Make a project reproducible for someone who has never seen it",
      "Read tidyverse code and map every verb onto its pandas equivalent",
      "Revise the whole course against a checklist before the written final",
    ],
    ru: [
      "Проводить разведочный анализ как повторяемую процедуру, а не импровизацию",
      "Делать проект воспроизводимым для человека, который видит его впервые",
      "Читать код на tidyverse и сопоставлять каждый глагол с аналогом в pandas",
      "Повторить весь курс по чек-листу перед письменным экзаменом",
    ],
  },
  sections: [
    {
      heading: { en: "What the quiz and the final cover", ru: "Что на тесте и на финальном экзамене" },
      body: {
        en: [
          "The end-term quiz is 9–14 November and is worth 40 points, the other 60 having come from the project submitted last week. The written final in the session on 16–28 November covers the whole ten weeks and is worth 40 % of the course grade.",
          "Written means no editor and no search. Expect to write SQL by hand — a join with grouping and a HAVING clause, without autocomplete — to explain a Python semantics question such as mutable defaults or view versus copy, to name the normal forms and show a violation, and to describe a cleaning decision and defend it.",
        ],
        ru: [
          "Итоговый тест проходит 9–14 ноября и стоит 40 баллов; остальные 60 набраны проектом, сданным на прошлой неделе. Письменный финальный экзамен в сессию 16–28 ноября закрывает все десять недель и весит 40 % итоговой оценки за курс.",
          "Письменный — значит без редактора и без поиска. Готовься писать SQL от руки: соединение с группировкой и условием HAVING без автодополнения, объяснять вопрос по семантике Python вроде изменяемых значений по умолчанию или представления против копии, называть нормальные формы и показывать нарушение, а также описывать решение об очистке и обосновывать его.",
        ],
      },
      table: {
        head: { en: ["Weeks", "Must be able to", "Written-exam form"], ru: ["Недели", "Уметь", "Форма на письменном"] },
        rows: [
          ["1–2", "types, mutability, NumPy axes, broadcasting", "predict the output of a snippet"],
          ["3–4", "loc/iloc, masks, groupby, joins", "write the expression by hand"],
          ["5", "missingness, duplicates, outliers", "justify a cleaning decision"],
          ["6–7", "SELECT order, joins, NULL, 1NF–3NF, indexes", "write a query; normalise a table"],
          ["8–9", "parameterised queries, ETL, chart choice", "spot the injection; fix the chart"],
        ],
        rowsRu: [
          ["1–2", "типы, изменяемость, оси NumPy, broadcasting", "предсказать вывод фрагмента"],
          ["3–4", "loc/iloc, маски, groupby, соединения", "написать выражение от руки"],
          ["5", "пропуски, дубликаты, выбросы", "обосновать решение об очистке"],
          ["6–7", "порядок SELECT, соединения, NULL, 1НФ–3НФ, индексы", "написать запрос; нормализовать таблицу"],
          ["8–9", "параметризованные запросы, ETL, выбор графика", "найти инъекцию; починить график"],
        ],
      },
    },
    {
      heading: { en: "EDA as a procedure", ru: "Разведочный анализ как процедура" },
      body: {
        en: [
          "Exploratory data analysis has a reputation for being improvisation. It is more useful to treat it as a fixed sequence, because a fixed sequence is what stops you from missing the thing that later invalidates your conclusion.",
          "The order that works: understand the shape and the types; quantify what is missing and why; check each variable one at a time — distribution, outliers, impossible values; then check pairs — correlations, cross-tabulations, group differences; then check time, if the data have any; and finally state the hypotheses the exploration produced.",
          "That last step is what separates exploration from analysis, and it matters for honesty. Hypotheses generated by looking at the data cannot be tested on the same data — the p-values would be meaningless, because the data chose the question. Say explicitly which findings are exploratory and would need fresh data to confirm.",
        ],
        ru: [
          "У разведочного анализа репутация импровизации. Полезнее относиться к нему как к фиксированной последовательности, потому что именно фиксированная последовательность не даёт пропустить то, что потом обесценит вывод.",
          "Работающий порядок: понять форму и типы; измерить, чего не хватает и почему; проверить каждую переменную по отдельности — распределение, выбросы, невозможные значения; затем проверить пары — корреляции, таблицы сопряжённости, различия между группами; затем проверить время, если оно в данных есть; и наконец сформулировать гипотезы, которые породила разведка.",
          "Последний шаг и отделяет разведку от анализа, и он важен для честности. Гипотезы, порождённые разглядыванием данных, нельзя проверять на тех же данных: p-значения окажутся бессмысленными, потому что вопрос выбрали сами данные. Прямо указывай, какие находки разведочные и требуют новых данных для подтверждения.",
        ],
      },
      code: {
        lang: "python",
        caption: { en: "A reusable EDA skeleton", ru: "Переиспользуемый скелет EDA" },
        code: `def eda(df, target=None, cats=(), time_col=None):
    print("=== 1. форма и типы ===")
    print(df.shape); print(df.dtypes)

    print("\\n=== 2. пропуски ===")
    na = (df.isna().mean() * 100).round(1)
    print(na[na > 0].sort_values(ascending=False))

    print("\\n=== 3. по одной переменной ===")
    print(df.describe().T[["min", "25%", "50%", "75%", "max"]].round(2))
    for c in cats:
        print(f"\\n{c}:"); print(df[c].value_counts(dropna=False).head(10))

    print("\\n=== 4. попарно ===")
    num = df.select_dtypes("number")
    if target and target in num:
        print(num.corr()[target].drop(target)
                 .sort_values(key=abs, ascending=False).round(3))

    print("\\n=== 5. время ===")
    if time_col:
        print(df[time_col].min(), "->", df[time_col].max())
        print(df.set_index(time_col).resample("W").size().describe())

    print("\\n=== 6. качество ===")
    print("полных дублей:", df.duplicated().sum())
    print("константных столбцов:", [c for c in df if df[c].nunique(dropna=False) <= 1])

eda(df, target="revenue", cats=["country", "device"], time_col="created_at")`,
        out: {
          en: "Constant columns and 100 % missing columns are the two things that quietly break models later. Catching them in step six costs nothing.",
          ru: "Константные столбцы и столбцы, пустые на 100 %, — две вещи, которые потом тихо ломают модели. Поймать их на шестом шаге не стоит ничего.",
        },
      },
      pitfall: {
        en: "Finding a pattern by exploring and then testing it on the same rows is a form of p-hacking, even when unintentional. If a hypothesis came from the data, it needs new data — or at minimum, say in the report that it is exploratory.",
        ru: "Найти закономерность разведкой и проверить её на тех же строках — форма p-хакинга, даже непреднамеренная. Если гипотеза пришла из данных, ей нужны новые данные — или хотя бы честная пометка в отчёте, что находка разведочная.",
      },
    },
    {
      heading: { en: "Reproducibility is part of the deliverable", ru: "Воспроизводимость — часть сдаваемой работы" },
      body: {
        en: [
          "A result nobody else can reproduce is not a result. The test is simple: could a stranger clone your repository and get your numbers? Everything below is in service of that one question.",
          "Pin the environment, so the packages are the versions you used. Fix every random seed. Use relative paths only. Provide the data or a script that downloads it. Keep the notebook runnable top to bottom from a clean kernel. Write a README saying what the project does, how to run it, and where the data came from.",
          "Notebooks fight reproducibility by design, because cells can run in any order and the output you see may come from code you have since deleted. Restart Kernel and Run All before every commit that matters. For anything that will be re-run regularly, move the logic into .py modules and keep the notebook as a thin presentation layer — the code becomes testable and reviewable in a diff.",
        ],
        ru: [
          "Результат, который никто не может воспроизвести, — не результат. Проверка проста: сможет ли посторонний склонировать твой репозиторий и получить твои числа? Всё нижеследующее служит этому одному вопросу.",
          "Зафиксируй окружение, чтобы версии пакетов были теми, на которых ты работал. Зафиксируй все random seed. Используй только относительные пути. Приложи данные или скрипт, который их скачивает. Держи ноутбук проходимым сверху донизу с чистого ядра. Напиши README о том, что проект делает, как его запустить и откуда данные.",
          "Ноутбуки сопротивляются воспроизводимости по своей конструкции: ячейки выполняются в любом порядке, а увиденный вывод может происходить из кода, который ты уже удалил. Делай Restart Kernel и Run All перед каждым значимым коммитом. Для всего, что будет регулярно перезапускаться, вынеси логику в .py модули, а ноутбук оставь тонким слоем представления — код станет тестируемым и читаемым в диффе.",
        ],
      },
      code: {
        lang: "text",
        caption: { en: "What a finished project looks like", ru: "Как выглядит законченный проект" },
        code: `project/
├── README.md              что делает, как запустить, откуда данные, что найдено
├── requirements.txt       или pyproject.toml — зафиксированные версии
├── data/
│   ├── raw/               скачивается скриптом, в git не коммитится
│   └── processed/         результат очистки, воспроизводим
├── sql/
│   ├── schema.sql         DDL со всеми ограничениями
│   └── report.sql         аналитические запросы
├── src/
│   ├── clean.py           логика очистки, импортируется ноутбуком
│   └── etl.py             извлечение, преобразование, загрузка
├── notebooks/
│   └── 01_analysis.ipynb  тонкий слой: импорт, вызов, график, вывод
└── figures/               экспортированные графики для отчёта`,
      },
    },
    {
      heading: { en: "R and the tidyverse, in one section", ru: "R и tidyverse за один раздел" },
      body: {
        en: [
          "The syllabus names R alongside Python and lists R for Data Science in the reading. You do not need to become an R programmer, but you should be able to read tidyverse code, because a great deal of statistical work is published in it.",
          "The tidyverse is a small set of verbs chained with a pipe. filter keeps rows, select keeps columns, mutate adds columns, arrange sorts, group_by plus summarise aggregates. Every one of them has a direct pandas equivalent, so the concepts transfer completely — only the syntax is new.",
          "The pipe |> passes the left-hand result as the first argument of the right-hand function, which makes a chain read as a sequence of steps in the order they happen. pandas achieves the same readability with method chaining inside parentheses, and the comparison is worth seeing side by side once.",
        ],
        ru: [
          "Силлабус называет R наравне с Python, а в литературе стоит R for Data Science. Становиться R-программистом не нужно, но уметь читать код на tidyverse стоит: очень много статистической работы публикуется именно на нём.",
          "Tidyverse — небольшой набор глаголов, соединяемых конвейером. filter оставляет строки, select оставляет столбцы, mutate добавляет столбцы, arrange сортирует, group_by вместе с summarise агрегирует. У каждого есть прямой аналог в pandas, поэтому понятия переносятся полностью — нов только синтаксис.",
          "Конвейер |> передаёт результат слева первым аргументом функции справа, отчего цепочка читается как последовательность шагов в порядке их выполнения. pandas добивается той же читаемости цепочкой методов внутри скобок, и это сравнение стоит один раз увидеть рядом.",
        ],
      },
      table: {
        head: { en: ["tidyverse", "pandas", "does"], ru: ["tidyverse", "pandas", "что делает"] },
        rows: [
          ["filter(x > 5)", "df[df.x > 5]", "keeps rows"],
          ["select(a, b)", "df[['a','b']]", "keeps columns"],
          ["mutate(z = x * y)", "df.assign(z=df.x * df.y)", "adds a column"],
          ["arrange(desc(x))", "df.sort_values('x', ascending=False)", "sorts"],
          ["group_by(g) |> summarise(m = mean(x))", "df.groupby('g')['x'].mean()", "aggregates"],
          ["left_join(b, by = 'id')", "a.merge(b, on='id', how='left')", "joins"],
        ],
        rowsRu: [
          ["filter(x > 5)", "df[df.x > 5]", "оставляет строки"],
          ["select(a, b)", "df[['a','b']]", "оставляет столбцы"],
          ["mutate(z = x * y)", "df.assign(z=df.x * df.y)", "добавляет столбец"],
          ["arrange(desc(x))", "df.sort_values('x', ascending=False)", "сортирует"],
          ["group_by(g) |> summarise(m = mean(x))", "df.groupby('g')['x'].mean()", "агрегирует"],
          ["left_join(b, by = 'id')", "a.merge(b, on='id', how='left')", "соединяет"],
        ],
      },
      code: {
        lang: "text",
        caption: { en: "The same pipeline in both languages", ru: "Один конвейер на обоих языках" },
        code: `# R / tidyverse
orders |>
  filter(created_at >= "2026-01-01") |>
  left_join(customers, by = "customer_id") |>
  group_by(country) |>
  summarise(orders = n(), revenue = sum(total)) |>
  arrange(desc(revenue))

# Python / pandas — те же шаги, тот же порядок чтения
(orders
   .query("created_at >= '2026-01-01'")
   .merge(customers, on="customer_id", how="left")
   .groupby("country", as_index=False)
   .agg(orders=("order_id", "size"), revenue=("total", "sum"))
   .sort_values("revenue", ascending=False))`,
        out: {
          en: "Wrapping a pandas chain in parentheses lets you break it across lines and read it as a pipeline. It is the closest pandas gets to the pipe.",
          ru: "Оборачивание цепочки pandas в скобки позволяет разбить её по строкам и читать как конвейер. Это ближайшее, что есть в pandas к конвейеру R.",
        },
      },
    },
  ],
  worked: {
    title: { en: "Worked example: an EDA that changed the question", ru: "Разбор: разведка, изменившая вопрос" },
    intro: {
      en: "You are asked which marketing channel gives the highest average order value. Run the EDA before answering, and watch the question change.",
      ru: "Тебя просят выяснить, какой маркетинговый канал даёт наибольшую среднюю сумму заказа. Проведи разведку до ответа и посмотри, как вопрос изменится.",
    },
    steps: [
      {
        text: { en: "The naive answer takes ten seconds and is where most people stop.", ru: "Наивный ответ занимает десять секунд, и на нём большинство останавливается." },
        code: { lang: "python", code: `print(df.groupby("channel")["order_total"].mean().sort_values(ascending=False))
# email 14200, direct 9800, social 4100` },
      },
      {
        text: { en: "Step two of the EDA: how much is missing, and is it missing evenly across channels?", ru: "Второй шаг разведки: сколько пропусков и равномерно ли они распределены по каналам?" },
        code: {
          lang: "python",
          code: `print(df.groupby("channel")["order_total"].apply(lambda s: s.isna().mean()).round(3))
# email 0.02, direct 0.05, social 0.41   <- сорок один процент!`,
        },
      },
      {
        text: { en: "Step three: the distribution, not the mean. Compare mean against median — the week-1 skew test from the maths course.", ru: "Третий шаг: распределение, а не среднее. Сравним среднее с медианой — тест на скошенность из первой недели курса математики." },
        code: {
          lang: "python",
          code: `print(df.groupby("channel")["order_total"].agg(["mean", "median", "count"]).round(0))
# email:  mean 14200, median 3100, n=480   <- среднее в 4.5 раза выше медианы`,
        },
      },
      {
        text: { en: "Find what is dragging the mean. A handful of corporate orders sit in one channel.", ru: "Найдём, что тянет среднее. Горстка корпоративных заказов сидит в одном канале." },
        code: {
          lang: "python",
          code: `big = df[df.order_total > 100_000]
print(len(big), big.groupby("channel").size().to_dict())
# 7 заказов, все семь в канале email`,
        },
      },
      {
        text: { en: "Re-answer with the median, and check whether the ranking survives.", ru: "Отвечаем заново по медиане и проверяем, выживает ли ранжирование." },
        code: {
          lang: "python",
          code: `print(df.groupby("channel")["order_total"].median().sort_values(ascending=False))
# direct 4900, email 3100, social 2800   <- порядок изменился`,
        },
      },
    ],
    conclusion: {
      en: "The exploration overturned the answer twice. Seven corporate orders made email look three times better than it is, and 41 % of social orders have no recorded value at all, so its number cannot be compared with the others until that is explained. The honest report gives medians, names the seven outliers, flags the missingness in social as a data-collection problem, and says that the original question cannot be answered for social until it is fixed. That is a more useful deliverable than a ranking that happens to be wrong.",
      ru: "Разведка дважды перевернула ответ. Семь корпоративных заказов сделали email втрое лучше, чем он есть, а у 41 % заказов из social сумма вообще не записана, поэтому его число несопоставимо с остальными, пока это не объяснено. Честный отчёт даёт медианы, называет семь выбросов, помечает пропуски в social как проблему сбора данных и говорит, что для social исходный вопрос не имеет ответа, пока проблема не устранена. Это более полезный результат, чем ранжирование, которое случайно оказалось неверным.",
    },
  },
  exercises: [
    {
      q: { en: "Why can you not test a hypothesis on the same data that suggested it?", ru: "Почему нельзя проверять гипотезу на тех же данных, которые её подсказали?" },
      a: { en: "Because the data already selected the hypothesis, so the p-value no longer means what it claims. If you scan fifty variables and test the one with the biggest difference, you have implicitly run fifty tests and kept the most extreme, which makes a small p-value expected under pure noise. Either hold out a validation set from the start, confirm on new data, or label the finding as exploratory and requiring confirmation. The last option is legitimate and honest.", ru: "Потому что данные уже отобрали гипотезу, и p-значение больше не означает заявленного. Если просмотреть пятьдесят переменных и проверить ту, где различие наибольшее, ты неявно провёл пятьдесят тестов и оставил самый экстремальный, а тогда малое p-значение ожидаемо и при чистом шуме. Либо отложи проверочную выборку с самого начала, либо подтверждай на новых данных, либо пометь находку как разведочную и требующую подтверждения. Последний вариант законен и честен." },
    },
    {
      q: { en: "A colleague cannot reproduce your numbers. Name four likely causes.", ru: "Коллега не может воспроизвести твои числа. Назови четыре вероятные причины." },
      a: { en: "An unfixed random seed, so any sampling or model differs run to run. Cells executed out of order, so your kernel holds state that a clean run does not produce. Absolute paths or data that only exists on your machine. And package versions differing, since a default argument or an algorithm can change between releases. Fix all four: set seeds, Restart and Run All, relative paths with a download script, and pinned requirements.", ru: "Незафиксированный random seed, из-за чего любая выборка или модель отличается от запуска к запуску. Ячейки, выполненные не по порядку, из-за чего в твоём ядре живёт состояние, которого чистый запуск не даёт. Абсолютные пути или данные, существующие только на твоей машине. И разные версии пакетов, поскольку аргумент по умолчанию или алгоритм могут поменяться между релизами. Чини все четыре: фиксируй seed, делай Restart и Run All, относительные пути со скриптом загрузки, зафиксированные зависимости." },
    },
    {
      q: { en: "Translate to pandas: data |> filter(x > 0) |> group_by(g) |> summarise(m = mean(y))", ru: "Переведи в pandas: data |> filter(x > 0) |> group_by(g) |> summarise(m = mean(y))" },
      a: { en: "data[data.x > 0].groupby('g', as_index=False).agg(m=('y', 'mean')), or in chained style data.query('x > 0').groupby('g', as_index=False).agg(m=('y','mean')). Every tidyverse verb has a direct counterpart: filter is boolean masking or query, group_by plus summarise is groupby plus agg, and as_index=False plays the role of ungrouping the result.", ru: "data[data.x > 0].groupby('g', as_index=False).agg(m=('y', 'mean')) либо в цепочечном стиле data.query('x > 0').groupby('g', as_index=False).agg(m=('y','mean')). У каждого глагола tidyverse есть прямой аналог: filter — булева маска или query, group_by с summarise — groupby с agg, а as_index=False играет роль разгруппировки результата." },
    },
    {
      q: { en: "Your EDA finds a column that is 100 % identical in every row. What do you do?", ru: "Разведка находит столбец, одинаковый во всех строках. Что делать?" },
      a: { en: "Drop it, but investigate first. A constant column carries no information and can break some models, so it should not enter the analysis. But the reason it is constant may matter: it might indicate that your extract accidentally filtered to a single category, that a feature flag was never switched on, or that an upstream join collapsed the data. A constant where you expected variety is a data-collection finding, not just a column to delete.", ru: "Удалить, но сначала разобраться. Константный столбец не несёт информации и способен сломать некоторые модели, поэтому в анализ ему не место. Но причина постоянства может быть важна: возможно, выгрузка случайно отфильтровалась до одной категории, флаг функции ни разу не включали или соединение выше по потоку схлопнуло данные. Константа там, где ждали разнообразия, — находка о сборе данных, а не просто столбец на удаление." },
    },
    {
      q: { en: "Why move logic from a notebook into .py modules?", ru: "Зачем выносить логику из ноутбука в .py модули?" },
      a: { en: "Because a module can be imported, tested, reviewed in a diff and reused, none of which a notebook cell supports well. Notebooks also hide execution order, so the output you see may come from deleted code. The usual arrangement keeps cleaning and ETL functions in src/, imports them into the notebook, and leaves the notebook as a thin layer of calls, plots and interpretation — which is also far easier for a marker to read.", ru: "Потому что модуль можно импортировать, тестировать, вычитывать в диффе и переиспользовать, а ячейка ноутбука ничего из этого толком не поддерживает. Ноутбуки вдобавок скрывают порядок выполнения, поэтому увиденный вывод может происходить из удалённого кода. Обычное устройство: функции очистки и ETL лежат в src/, импортируются в ноутбук, а ноутбук остаётся тонким слоем вызовов, графиков и интерпретации — и это заодно много легче читать проверяющему." },
    },
    {
      q: { en: "One channel has 41 % missing order values. Can you compare its mean with the others?", ru: "У одного канала 41 % пропусков в суммах заказов. Можно ли сравнивать его среднее с остальными?" },
      a: { en: "No, not until you know why they are missing. The mean is computed over the 59 % that remain, so it describes a subset selected by an unknown mechanism. If large orders are the ones failing to record, the mean is biased downward; if small ones are, upward. Report the missingness rate next to every group statistic, investigate the cause, and say plainly that the comparison cannot be made until it is resolved.", ru: "Нет, пока не выяснено, почему они пропущены. Среднее считается по оставшимся 59 %, поэтому описывает подмножество, отобранное неизвестным механизмом. Если не записываются крупные заказы, среднее смещено вниз; если мелкие — вверх. Указывай долю пропусков рядом с каждой групповой статистикой, выясняй причину и прямо пиши, что сравнение невозможно, пока вопрос не решён." },
    },
  ],
  checklist: {
    en: [
      "I have an EDA function I run on every new dataset",
      "A stranger could clone my repository and reproduce my numbers",
      "My notebook runs top to bottom from a clean kernel, with seeds fixed",
      "I can read a tidyverse pipeline and name the pandas equivalent of each verb",
      "I have revised all ten weeks against the table above and written the cheat sheet",
    ],
    ru: [
      "У меня есть функция EDA, которую я запускаю на каждом новом датасете",
      "Посторонний человек может склонировать репозиторий и воспроизвести мои числа",
      "Ноутбук проходит сверху донизу с чистого ядра, seed зафиксированы",
      "Могу прочитать конвейер на tidyverse и назвать аналог каждого глагола в pandas",
      "Повторил все десять недель по таблице выше и написал шпаргалку",
    ],
  },
};
